# Generated by Django 4.2.4 on 2023-08-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='discription',
            new_name='description',
        ),
    ]
